# Generated by Django 6.0.3 on 2026-04-03 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_alter_cliente_email_alter_empleado_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
