# Generated by Django 6.0.3 on 2026-04-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0005_alter_empleado_id_alter_empleado_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=50),
        ),
    ]
