# Generated by Django 6.0.3 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0006_alter_reserva_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaccion',
            name='tipo',
            field=models.CharField(choices=[('Llamada', 'Llamada'), ('Email', 'Email'), ('Reunión', 'Reunión')], default='Llamada', max_length=50),
        ),
    ]
