# Generated by Django 6.0.3 on 2026-04-10 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0007_alter_interaccion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaccion',
            name='fecha_interaccion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(),
        ),
    ]
